version: "3.7"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "4567:4567"
    stdin_open: true
    tty: true
    command: bundle exec ruby app.rb
    environment:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    links:
      - dynamo-admin
  dynamo-admin:
    image: instructure/dynamo-local-admin
    ports:
        - '8000:8000'
        - '8002:8002'